### ISSUE TITLE
Incorrect installation?

### ISSUE THREAD

**Issue by ghost** [fogine/i3-workscreen#4]
After following these install instructions from [the readme](https://github.com/fogine/i3-workscreen#installation):
`pip install git+https://github.com/fogine/i3-workscreen.git`

Running fails with `ImportError: No module named validationschema`

Any ideas?

**edit:** this is in Ubuntu 18.04 running Python 2.7. I confirmed the same behaviour in the `ubuntu:latest` container image [off Dockerhub](https://hub.docker.com/_/ubuntu) as well..

**Comment by fogine** [comment]
As stated in readme, it requires python 3.
Do you experience the same issue while running it with python 3?

**Comment by ghost** [comment]
Ah, woops. You could probably use something like [this](https://github.com/kennethreitz/setup.py/blob/master/setup.py#L103) to declare that..?

Anyway, it works in python3 for sure. Thanks!
