### ISSUE TITLE
Always throws 'No connected display outputs detected'

### ISSUE THREAD

**Issue by eug-vs** [fogine/i3-workscreen#8]
I have my HDMI (`HDMI1`) plugged in and connected to active monitor, but `i3-workscreen` throws this exception:
```
$ i3-workscreen
Traceback (most recent call last):
  File "/home/eug-vs/.local/bin/i3-workscreen", line 33, in <module>
    sys.exit(load_entry_point('i3-workscreen==1.0.0', 'console_scripts', 'i3-workscreen')())
  File "/home/eug-vs/.local/lib/python3.9/site-packages/i3workscreen/i3workscreen.py", line 189, in main
    outputCloneCandidate = getCloneCandidate(connectedOutputs)
  File "/home/eug-vs/.local/lib/python3.9/site-packages/i3workscreen/i3workscreen.py", line 137, in getCloneCandidate
    raise Exception('No connected display outputs detected.')
Exception: No connected display outputs detected.
```
My `xrandr` can see my `HDMI1` though, I can manually execute `$ xrandr --output HDMI1 --auto --left-of eDP1` and it works. Am I missing something? It has nothing to do with `udev` event as I understand. Here's my `config.json`:
```
$ cat ~/.config/i3-workscreen/config.json
{
    "disableEmptyOutputs": false,
    "outputs": [
        {
            "name": "eDP-1",
            "workspaces": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" ]
        },
        {
            "name": "HDMI-1",
            "xrandr": ["--left-of", "eDP-1"],
            "workspaces": [ "1", "2"]
        }
    ]
}
```

OS: Arch Linux
Python: 3.9.1

**Comment by fogine** [comment]
You probably have incorrect value for output name in the config `HDMI-1` as in your xrandr command you use `HDMI1`

**Comment by eug-vs** [comment]
Thank you! I copied config example from `README` and didn't notice that output names don't match. I removed all `-` symbols from output names as my xrandr expects and it works. Now I understand what the error message have been telling me :)

Thanks for the amazing project!
